When upgrade, change redis bind to lo and eth0.

diff --git a/mgmt/upgrade b/mgmt/upgrade
--- a/mgmt/upgrade
+++ b/mgmt/upgrade
@@ -36,6 +36,16 @@ if [[ ! -d /usr/local/srs-terraform && $(uname -s) == 'Darwin' ]]; then
   sleep 3; exit 0;
 fi
 
+# We must setup the redis to listen at lo and eth0, to allow containers to access it.
+# Note that should never listen at * for security reason.
+PIPV4=$(ifconfig eth0 |grep 'inet ' |awk '{print $2}')
+if [[ $PIPV4 == '' ]]; then echo 'No private IP of eth0'; exit 1; fi
+# Replace the bind for redis.
+sed -i "s/^bind 127.0.0.1.*$/bind 127.0.0.1 $PIPV4/g" /etc/redis.conf && grep '^bind 127.0.0.1' /etc/redis.conf &&
+sudo systemctl restart redis && sudo systemctl status redis &&
+echo "Change redis to listen at lo and eth0=$PIPV4"
+if [[ $? -ne 0 ]]; then echo "Listen at eth0=$PIPV4 for redis failed"; exit 1; fi
+
 # Try git stash first, ignore any error.
 git stash 2>>upgrade.error.log
 if [[ $? -ne 0 ]]; then
